### ISSUE TITLE
Allow configuration of "Event sources"

### ISSUE THREAD

**Issue by barbeau** [SeanRoy/lambda-maven-plugin#18]
This plugin is great for development workflow and quickly uploading code and configurations to Lambda.  

The one exception is "Event Sources".  Currently this is something we have to manually set on each upload - in our case, it's the "Alexa Skills Kit".

Is this something that could be configured via lambduh?

cc @philipmw

**Comment by SeanRoy** [comment]
Sorry, I've been away on travel, I'll look into this soon.

**Comment by SeanRoy** [comment]
I'm going to start working on this shortly.

**Comment by barbeau** [comment]
@SeanRoy Just curious - any ETA for this?

**Comment by kgrodzicki** [comment]
@barbeau from version 2 plugin has support for SNS "topics" and scheduled rules "scheduledRules", please refer to https://github.com/SeanRoy/lambda-maven-plugin/blob/master/README.md

**Comment by SeanRoy** [comment]
Hi Sean, thanks for your email.  I'm going to try to get this in by the end
of October.


sean@nrby.com <brittany.campbell@ping4.com>  | nrby.com
Twitter <https://twitter.com/nrbynow>  |  Facebook
<https://www.facebook.com/nrbynow>  |  Instagram
<https://instagram.com/nrbynow/>  |  LinkedIn
<http://linkedin.com/company/nrby>
<http://linkedin.com/company/nrby>

This message is intended only for the use of the individual or entity named
above and may contain information which is privileged, confidential, and
not intended for disclosure. If you are not the intended recipient, you are
hereby notified that any disclosure, copying, distribution, dissemination
or use of this message is strictly prohibited. If you have received this
message in error, please accept our apology. We would very much appreciate
your notifying the sender immediately by return email. Thank you.

**Comment by SeanRoy** [comment]
I've begun work on this.

**Comment by SeanRoy** [comment]
@barbeau I just deployed the alexa skills kit integration to 2.1.3.  Please note that this change just allows the lambda function to be triggered by alexa.  You'll still have to do the manual steps of putting the function arn in Alexa and the Alexa app id into the lambda function.  At this time I'm not sure there's a way to automate that. 
I'm still waiting for my amazon echo to do a true end to end test of this functionality.

**Comment by barbeau** [comment]
Awesome,  thanks,  I'll try this out!

**Comment by barbeau** [comment]
BTW,  here are some ways to test without physical Alexa device:
https://github.com/OneBusAway/onebusaway-alexa/blob/master/README.md#testing-without-an-alexa-device

Roger was the closest I could get,  although it's not perfect.

**Comment by SeanRoy** [comment]
How is this working out for you?  Can I close this issue?

**Comment by barbeau** [comment]
Sorry, haven't had a chance to try it yet - I've been having certification
issues with Amazon so I've been stuck in that state.  Feel free to close
and I'll reopen if it doesn't work when I try it.  Thanks for implementing
this!
