### ISSUE TITLE
Allow HTTP Proxy configuration?

### ISSUE THREAD

**Issue by xwjenny** [SeanRoy/lambda-maven-plugin#39]
Possible to support to set http_proxy and https_proxy from plugin configuration?

**Comment by SeanRoy** [comment]
Could you be more specific? What are you trying to accomplish?

**Comment by xwjenny** [comment]
Here is the details:

 I am using this plugin from inside company's internal network. 
 
I hope I could  explicitly specify HTTP proxy in the plugin configuration:
```
<groupId>com.github.seanroy</groupId>
<artifactId>lambda-maven-plugin</artifactId>
<version>2.1.0</version>
<configuration>
<protocol>https</protocol>
<proxyHost>a-proxy....net</proxyHost>
<proxyPort>1234</proxyPort>
```

This configuration will be translated to codes similar like below:

```
lambdaClient = of(credentials).map(
				credentials -> new AWSLambdaClient(credentials, getClientConfig()).<AWSLambdaClient>withRegion(region))
				.orElse(new AWSLambdaClient(getClientConfig()).withRegion(region));

private ClientConfigurationgetClientConfig() {
		ClientConfiguration clientConfig = new ClientConfiguration();
		clientConfig.setProtocol("https");
		clientConfig.setProxyHost("a-proxy....net");
		clientConfig.setProxyPort(11234);
		return clientConfig;
	}

```

I  tried other options to achieve the same effect, but they did not work out for me. Above codes work fine.

Thanks!

**Comment by SeanRoy** [comment]
@xwjenny This will fall under issue 10, AWS API Gateway integration.  It's on the roadmap, but I'm not sure when I'm going to get to it.  I'll try to make it a priority though.

**Comment by SeanRoy** [comment]
@xwjenny I'm really sorry it took me so long to get to this.  If you're still there, could you please grab 2.2.9 and test this out?  At the moment I don't have time to set up a test proxy to test this functionality.
