### ISSUE TITLE
The final policy size (20786) is bigger than the limit (20480)

### ISSUE THREAD

**Issue by kgrodzicki** [SeanRoy/lambda-maven-plugin#42]
Each deploy adds policy permission for lambda function. Deploy fails when policy size exceeds the limit.

`
com.amazonaws.services.lambda.model.PolicyLengthExceededException: The final policy size (20786) is bigger than the limit (20480). (Service: AWSLambda; Status Code: 400; Error Code: PolicyLengthExceededException; Request ID: 6bedc15d-9ceb-11e6-8889-dd864af63382)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1529)
`

**Comment by SeanRoy** [comment]
@kgrodzicki Are you working on fixing this or are you just reporting it?

**Comment by kgrodzicki** [comment]
I'm on it

**Comment by SeanRoy** [comment]
Cool, thank you.

**Comment by manoharreddyporeddy** [comment]
I am using gulp-awslambda instead.
The error looks to be of AWS lambda instead.

ISSUE:
Re-deploying an existing lambda is failing

SOLUTION:
1. delete lambda function
2. re-create it
