### ISSUE TITLE
Update $LATEST version

### ISSUE THREAD

**Issue by gmiano** [SeanRoy/lambda-maven-plugin#57]
Hello,
I really appreciate this maven plugin. Unfortunately every deployment would create a new Lambda version.
Is there a way to update $LATEST instead?

**Comment by SeanRoy** [comment]
Thanks for your request, I'm looking into it.

**Comment by SeanRoy** [comment]
I'm sorry I let this go so long.  All you have to do is set publish=false (<publish>false</publish>).   Publish defaults to true and when true, it publishes a new version on every deployment.  Setting it to false will only update $LATEST.
