### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by dwschulze** [SeanRoy/lambda-maven-plugin#69]
mvn clean install -DskipTests gives the following error:

Generating /home/dean/Downloads/src/lambda-maven-plugin/target/apidocs/index.html...
Generating /home/dean/Downloads/src/lambda-maven-plugin/target/apidocs/help-doc.html...
[INFO] Building jar: /home/dean/Downloads/src/lambda-maven-plugin/target/lambda-maven-plugin-2.2.2-javadoc.jar
[INFO] 
[INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ lambda-maven-plugin ---
gpg: no default secret key: secret key not available
gpg: signing failed: secret key not available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.618 s
[INFO] Finished at: 2017-08-11T15:17:17-06:00
[INFO] Final Memory: 39M/776M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project lambda-maven-plugin: Exit code: 2 -> [Help 1]
[ERROR]

**Comment by SeanRoy** [comment]
Create a signing cert with gpg --gen-key

**Comment by dwschulze** [comment]
That worked.

Why is that gpg cert needed?  I've never used an app that required that.

**Comment by SeanRoy** [comment]
It's not required to use this plugin, but if you're going to build it, you'll need it because I need to sign it when I publish it to maven central.
