### ISSUE TITLE
No plugin found for prefix 'lambda' in the current project ...

### ISSUE THREAD

**Issue by dwschulze** [SeanRoy/lambda-maven-plugin#70]
Now I'm getting the error when I try to use the plugin.  The plugin is installed in my local repo ~/.m2.

$ mvn package lambda:deploy-lambda
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] account-customer-service
[INFO] account-service
[INFO] customer-service
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (13 KB at 31.8 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 KB at 46.5 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] account-customer-service ........................... SKIPPED
[INFO] account-service .................................... SKIPPED
[INFO] customer-service ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.860 s
[INFO] Finished at: 2017-08-13T11:19:39-06:00
[INFO] Final Memory: 14M/605M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'lambda' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/dean/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[

**Comment by SeanRoy** [comment]
This looks like it might be a plugin prefix resolution problem.  Would you be so kind as to post your pom?  Additionally, you could try mvn package com.github.seanroy.lambda:deploy-lambda

**Comment by dwschulze** [comment]
Doing `mvn package com.github.seanroy.lambda:deploy-lambda` give the same error.  Here's my top level pom.xml:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>aws.examples.serverless</groupId>
	<artifactId>account-customer-service</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.6.1</version>
				<configuration>
					<encoding>UTF-8</encoding>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-lambda-java-events</artifactId>
			<version>1.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-lambda-java-core</artifactId>
			<version>1.1.0</version>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-lambda-java-log4j</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-s3</artifactId>
			<version>1.11.152</version>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-lambda</artifactId>
			<version>1.11.152</version>
		</dependency>
	</dependencies>
	<modules>
		<module>account-service</module>
		<module>customer-service</module>
	</modules>
</project>

```

Customer Service pom.xml:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>aws.examples.serverless</groupId>
		<artifactId>account-customer-service</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	
	<artifactId>customer-service</artifactId>
	  	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>2.3</version>
				<configuration>
					<createDependencyReducedPom>false</createDependencyReducedPom>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.github.seanroy</groupId>
				<artifactId>lambda-maven-plugin</artifactId>
				<version>2.2.2</version>
				<configuration>
					<accessKey>${aws.accessKey}</accessKey>
					<secretKey>${aws.secretKey}</secretKey>
					<functionCode>${project.build.directory}/${project.build.finalName}.jar</functionCode>
					<version>${project.version}</version>
					<lambdaRoleArn>arn:aws:iam::504084722442:role/lambda-execution-role</lambdaRoleArn>
					<!-- <s3Bucket>lambda-function-bucket-us-east-1-1498055423860</s3Bucket> -->
					<s3Bucket>arn:aws:s3:::serverless-lambda-function-bucket</s3Bucket>
					<publish>true</publish>
					<forceUpdate>true</forceUpdate>
					<lambdaFunctionsJSON>
						[
							{
								"functionName": "PostCustomerFunction",
								"description": "POST customer",
								"handler": "aws.serverless.example.customer.crud.PostCustomer",
								"timeout": 30,
								"memorySize": 256,
								"keepAlive": 10
							},
							{
								"functionName": "GetCustomerFunction",
								"description": "GET customer",
								"handler": "aws.serverless.example.customer.crud.GetCustomer",
								"timeout": 30,
								"memorySize": 256,
								"keepAlive": 30
							}
						]
					</lambdaFunctionsJSON>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

The account-service pom.xml is similar except for `<lambdaFunctionsJSON>`.

**Comment by SeanRoy** [comment]
Thanks.  Ordinarily in a multi module project where you're referencing plugins in sub modules, you'd want to add the lambda plugin in the parent's pluginManagement section so that it's in scope and then reference it again in the sub modules with their specific configuration details: (see https://blog.jdriven.com/2015/03/prevent-no-plugin-found-in-multi-module-maven/)
Unfortunately this can't be done at this time because lambda has required config parameters.  For the time being you can do this for each submodule:
mvn -pl <submodule> package lambda:deploy-lambda

ie

> mvn -pl account-service package lambda:deploy-lambda
> mvn -pl customer-service package lambda:deploy-lambda

**Comment by dwschulze** [comment]
That worked.  I also had to remove the prefix from my Bucket names (remove the "arn:aws:s3:::").  You can't just copy the bucket URL from the S3 console.

I recommend you add both of these fixes to the readme.md on the project page.
