### ISSUE TITLE
Possibility to update a lambda function

### ISSUE THREAD

**Issue by fahu** [SeanRoy/lambda-maven-plugin#71]
Hi there! First off all thanks for the awesome plugin.

I'm using your plugin to upload an Alexa Skill to S3 and update it's lambda function which is working pretty good. However everytime executing the plugin the triggers are created in the lambda functions (the 'old one' is not deleted). Which means if you execute the function 10x there are 10 triggers added to it.

I guess that your plugin should only be used to add a new lambda function and not to update an existing one, however I really would appreciate if it would get full support to update existing functions.

Best Regards
Fabian

**Comment by SeanRoy** [comment]
I'm on it.

**Comment by SeanRoy** [comment]
This will be released shortly.

**Comment by SeanRoy** [comment]
This is fixed in 2.2.3.  You'll have to do one of two things:
- Delete your lambda function and re-deploy it
or
- Go into the aws web console and delete all of the alexa skills kit triggers, then redeploy.

After the redeploy, you'll only see one alexa skills kit from now on.

**Comment by fahu** [comment]
Awesome! Thank you very much for fixing it that fast.
