### ISSUE TITLE
NPE in cleanUpOrphanedAlexaSkillsTriggers at line 537

### ISSUE THREAD

**Issue by Gerben** [SeanRoy/lambda-maven-plugin#77]
When running mojo deploy-lambda for a redeploy an NPE occurs in method cleanUpOrphanedAlexaSkillsTriggers at line 537.
lambdaFunction.getExistingPolicy().getStatements().stream()

The lambda function I was trying to deploy has no policy. So getStatement() on getExistingPolicy() throws an NPE.

**Comment by SeanRoy** [comment]
Watch for 2.2.5, it sometimes takes an hour or two to show up in maven central.
