### ISSUE TITLE
Environment variables are trashed on deploy

### ISSUE THREAD

**Issue by blasd** [SeanRoy/lambda-maven-plugin#84]
Hello,

It appears environment variables filled manually in [https://console.aws.amazon.com/lambda/home](url) are trashed on each lambda deployment. I guess the plugin should not remove existing environment variables if the plugin config has not environment variable (and if the plugin has environment variables, I suppose they should be pushed to AWS-Lambda without removing existing ones).

**Comment by SeanRoy** [comment]
Thanks, I'll take a look.

**Comment by SeanRoy** [comment]
Fixed in 2.3.0.

**Comment by blasd** [comment]
Thanks
